dmce: use xz as pkg fmt

diff --git a/projects/dmce/distcheck b/projects/dmce/distcheck
--- a/projects/dmce/distcheck
+++ b/projects/dmce/distcheck
@@ -4,48 +4,8 @@ set -e
 
 export OVE_LOCAL_ECHO=1
 
-if [ -d "${OVE_ARCHIVE_DIR:?}" ]; then
-	# remove any old DMCE packages laying around
-	find "${OVE_ARCHIVE_DIR:?}" -mindepth 1 -mindepth 1 -name 'dmce-*.deb' -exec rm -v {} \;
-fi
-ove dist dmce
-
-cd "${OVE_BASE_DIR:?}"/dmce
-
-if [[ "${OVE_OS_ID_LIKE}" == *debian* ]]; then
-	d="$(find "${OVE_ARCHIVE_DIR:?}" -mindepth 1 -mindepth 1 -name 'dmce-*.deb' -type f)"
-	if [ "x${d}" = "x" ]; then
-		echo "error: DMCE package not found"
-		exit 1
-	fi
-
-	if [ "$OVE_OS" == "Ubuntu" ] && [ "$OVE_OS_VER" == "16.04" ]; then
-		_local=1
-	elif [ ${EUID} -ne 0 ]; then
-		_local=1
-	else
-		_local=0
-	fi
-
-	if [ $_local -eq 1 ]; then
-		if ! dpkg-deb -x "${d}" "${OVE_STAGE_DIR:?}"; then
-			echo "error: 'dpkg -x ${d} ${OVE_STAGE_DIR}' failed"
-			exit 1
-		elif ! dmce-configure-local; then
-			echo "error: 'dmce-configure-local' failed"
-			exit 1
-		fi
-	else
-		if ! dpkg -i "${d}"; then
-			echo "error: 'dpkg -i ${d}' failed"
-			exit 1
-		elif ! dmce-setup; then
-			echo "error: 'dmce-setup' failed"
-			exit 1
-		fi
-	fi
-elif ! ./dmce-configure-local; then
-	echo "error: 'dmce-configure-local' failed"
+if ! command -v dmce; then
+	echo "error: command 'dmce' missing"
 	exit 1
 fi
 
diff --git a/projects/dmce/install b/projects/dmce/install
--- a/projects/dmce/install
+++ b/projects/dmce/install
@@ -4,30 +4,23 @@ set -e
 
 if [ -d "${OVE_ARCHIVE_DIR:?}" ]; then
 	# remove any old DMCE packages laying around
-	find "${OVE_ARCHIVE_DIR:?}" -mindepth 1 -mindepth 1 -name 'dmce-*.deb' -exec rm {} \;
+	find "${OVE_ARCHIVE_DIR:?}" -mindepth 1 -mindepth 1 -name 'dmce-*' -exec rm {} \;
 fi
 
 if ! ove-dist dmce; then
 	exit 1
-fi
-
-d="$(find "${OVE_ARCHIVE_DIR:?}" -mindepth 1 -mindepth 1 -name 'dmce-*.deb' -type f)"
-if [ "x${d}" = "x" ]; then
+elif ! d="$(find "${OVE_ARCHIVE_DIR:?}" -mindepth 1 -mindepth 1 -name 'dmce-*.xz' -type f)"; then
+	exit 1
+elif [ "x${d}" = "x" ]; then
 	echo "error: DMCE package not found"
 	exit 1
-fi
-
-if ! dpkg-deb -x "$d" "$OVE_STAGE_DIR"; then
-	echo "error: 'dpkg-deb -x $d $OVE_STAGE_DIR' failed"
+elif ! tar -C "$OVE_STAGE_DIR" -xf "${d}"; then
+	echo "error: unpack '$d' failed"
 	exit 1
-fi
-
-if ! command -v dmce-setup > /dev/null; then
+elif ! command -v dmce-setup > /dev/null; then
 	echo "error: 'dmce-setup' not found"
 	exit 1
-fi
-
-if ! dmce-setup "$OVE_BASE_DIR"; then
+elif ! dmce-setup "$OVE_BASE_DIR"; then
 	echo "error: 'dmce-setup $OVE_BASE_DIR' failed"
 	exit 1
 fi
